const repo = 'https://github.com/CatInTheRiceHat/Chrysalis';
const issues = `${repo}/issues`;
const link = (href, text) => `<a href="${href}">${text}</a>`;
export function layout(route, { title, description = 'Plan your YouTube session, notice your time, and choose what comes next. Chrysalis is a local-first Chrome extension for desktop YouTube.', content }) {
  const nav = [['/', 'Overview'], ['/install', 'Install'], ['/privacy', 'Privacy'], ['/contact', 'Contact']];
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="${description}"><meta name="color-scheme" content="light dark"><title>${title} · Chrysalis</title><link rel="icon" href="/assets/logo.png"><link rel="stylesheet" href="/assets/site.css"><script src="/assets/site.js" defer></script></head><body>
<a class="skip" href="#main">Skip to content</a><header class="header wrap"><a class="brand" href="/" aria-label="Chrysalis home"><img src="/assets/logo.png" width="40" height="40" alt=""><span>Chrysalis</span></a><button class="menu-toggle" aria-expanded="false" aria-controls="navigation" hidden>Menu</button><nav id="navigation" aria-label="Main">${nav.map(([href, label]) => `<a href="${href}"${href === route ? ' aria-current="page"' : ''}>${label}</a>`).join('')}</nav><button class="theme-toggle" hidden aria-label="Change color theme">Theme: system</button></header>
<main id="main" class="wrap" tabindex="-1">${content}</main><footer class="wrap footer"><div><a class="wordmark" href="/">Chrysalis</a><p>A little intention. Your time, your choice.</p></div><div class="footer-links">${link('/legacy', 'The original project')}${link(issues, 'Project on GitHub')}${link('/privacy', 'Privacy & your data')}</div><p class="fineprint">Independent project by Elaine Che. For desktop YouTube in Chrome. Not affiliated with or endorsed by YouTube or Google.</p></footer></body></html>`;
}
export function pages(privacy) {
  return {
    '/': { title: 'YouTube, on your terms', content: `
<section class="hero"><div class="hero-copy"><p class="eyebrow"><span class="dot"></span> Desktop YouTube · Chrome extension</p><h1>A little intention.<br><em>A different kind<br>of YouTube time.</em></h1><p class="lead">Come for a tutorial. Stay for something you love. Chrysalis helps you notice your time and choose what comes next.</p><div class="actions"><a class="button" href="/install">Install Chrysalis <span aria-hidden="true">↗</span></a><a class="text-link" href="#how-it-works">Take a closer look <span aria-hidden="true">↓</span></a></div><p class="caption">Free developer preview. No account. No analytics.</p></div><figure class="hero-art"><div class="orbit"><img src="/assets/logo.png" width="380" height="380" alt="Chrysalis butterfly with warm purple and blue wings"></div><figcaption>More room to choose.<br>More space to be you.</figcaption></figure></section>
<section class="intro-line" aria-label="Our approach"><p>You don’t need to earn your downtime.</p><p>Entertainment, learning and a little wandering all belong here. Your plan can change. Your time stays yours.</p></section>
<section id="how-it-works" class="features"><div class="section-heading"><p class="eyebrow">A small presence, on your side</p><h2>Make space for<br>your next choice.</h2></div><div class="feature-list"><article><span class="number">01</span><div><h3>Begin with a thought.</h3><p>A centered introduction offers a time target and an optional intention. Start a session, or continue without a timer. It remembers your visit across pages and tabs.</p></div></article><article><span class="number">02</span><div><h3>Notice time passing.</h3><p>A compact timer sits near the side of YouTube. Hide it when you want the space; restore it when you want a glance. It counts foreground YouTube use, including browsing.</p></div></article><article><span class="number">03</span><div><h3>Choose what comes next.</h3><p>At your target, a check-in offers more time, a break, or a finish. Dismiss it or continue untimed. YouTube playback continues. There are no scores or penalties.</p></div></article></div></section>
<section class="choice-panel"><p class="eyebrow">Your viewing preferences</p><h2>A little less distraction.<br>Only if you want it.</h2><p>Choose which supported Home recommendations, related videos and Shorts entry points to hide. Everything starts visible. Restore the ordinary layout at any time.</p><p class="caption">Controls work on recognized layouts. Direct Shorts links remain available; Chrysalis does not change YouTube’s recommendation algorithm.</p><a class="text-link" href="/install#first-session">Explore your first session <span aria-hidden="true">↗</span></a></section>
<section class="closing"><div><p class="eyebrow">Private by design, clear about limits</p><h2>Your reflections<br>stay with you.</h2></div><div><p>Plans, preferences and up to 100 session summaries stay in Chrome’s local extension storage. Nothing is uploaded by the extension. Delete a summary, clear history, or reset everything.</p><p>Your intention is visible to YouTube when shown in its page. Local storage is not encrypted by Chrysalis.</p><a class="text-link" href="/privacy">Read the privacy explanation <span aria-hidden="true">↗</span></a></div></section>` },
    '/install': { title: 'Install the developer preview', content: `<section class="reading"><p class="eyebrow">A small addition to your browser</p><h1>Make yourself<br>at home.</h1><p class="lead">Chrysalis is a developer preview for desktop Chrome and <strong>www.youtube.com</strong>. It is not published in the Chrome Web Store yet.</p><aside class="note"><strong>Choose a trusted copy.</strong> Use preview files supplied by the project, or build from the ${link(repo, 'public source repository')}. This site does not offer an automatic installer. A ZIP alone is not a Chrome installation.</aside><h2>Install preview files</h2><ol class="steps"><li><strong>Extract the supplied ZIP.</strong> Keep the folder somewhere permanent. Open it and check that <code>manifest.json</code> is directly inside.</li><li><strong>Open Chrome’s Extensions page.</strong> Type <code>chrome://extensions</code> into the address bar and enable Developer mode.</li><li><strong>Choose Load unpacked.</strong> Select the extracted folder. Pin Chrysalis from Chrome’s Extensions menu.</li><li><strong>Open or refresh YouTube.</strong> The first foreground visit offers a session introduction. No Google login, Chrysalis account or API key is required.</li></ol><p>If a managed browser prevents developer extensions, use an eligible personal profile or contact its administrator.</p><details><summary>Build from source instead</summary><p>Install Git with Git LFS, Node 20 or newer, and Python 3. From a trusted checkout:</p><pre><code>git clone https://github.com/CatInTheRiceHat/Chrysalis.git
cd Chrysalis
git lfs pull
cd extension
npm ci
npm run check
npm run package</code></pre><p>Load <code>extension/dist/</code> from the checkout, or the extracted package in <code>extension/release/</code>. Keep that path stable. Initial development dependencies require internet; installed Chrysalis needs no project server.</p></details><h2 id="first-session">Your first session</h2><p>Choose 5, 15, 30 or 60 minutes, or a custom duration. An intention is optional. “Continue without a timer” dismisses the introduction and creates no session. The toolbar popup also lets you start an untimed session.</p><p>A new visit begins after about 30 minutes away from foreground YouTube. Refreshes, ordinary navigation and extra tabs share the visit. An unfinished session suppresses new introductions. You can turn automatic introductions off in settings.</p><p>Expand the side timer for your plan and controls. Hide leaves a restore tab and keeps timing. At your target, choose more time, a break, finish, or dismiss. Breaks end paused; Resume is always your choice.</p><p>In <strong>Viewing preferences</strong>, choose supported surfaces to hide. <strong>Restore ordinary layout</strong> reverses those choices. <strong>Pause Chrysalis</strong> restores the layout and stops session timing while keeping your settings.</p><h2>Update without losing your local history</h2><p>Keep the same installation folder and extension entry. Replace its files with the newer verified package, click <strong>Reload</strong> on <code>chrome://extensions</code>, and refresh YouTube. Do not remove and reinstall or add a second copy as an update.</p><p>Version 0.8.0 uses storage schema 7 and preserves valid earlier data. An older build may not read newer storage: downgrading is not a recovery method. No cloud backup or history export is included.</p><h2>When something feels off</h2><p>Check that you are on desktop <code>www.youtube.com</code>, the extension is enabled, and Chrome allows its site access. Refresh an existing YouTube tab after installing or updating. Unfamiliar layouts remain visible.</p><p>Time measures foreground browsing and watching, not attention or precise watch time. After a restart or uncertain timing gap, a session may be paused: open Chrysalis and choose Resume when ready.</p><p>${link('/contact', 'Get help or share feedback')} · ${link('/privacy', 'Understand local data and deletion')}</p></section>` },
    '/privacy': { title: 'Privacy and your data', content: `<section class="reading privacy"><p class="eyebrow">Clear about what stays local</p><h1>Your data.<br>Your choices.</h1>${privacy}<h2>This public website</h2><p>This site contains no analytics scripts, advertising, account system or feedback form. It stores only your chosen color theme in this browser. Its hosting provider may process ordinary request information when serving pages; this is separate from the extension’s local storage. Opening GitHub or your email application uses that service’s own policies.</p></section>` },
    '/contact': { title: 'Contact and feedback', content: `<section class="reading"><p class="eyebrow">An open conversation</p><h1>What’s working?<br>What could feel better?</h1><p class="lead">Chrysalis is a small independent project by Elaine Che. Questions, bugs and thoughtful feedback help shape the next version.</p><div class="contact-choice"><h2>Report an issue</h2><p>The public GitHub issue tracker is the place for reproducible bugs and feature suggestions. Check existing issues first. Posting requires a GitHub account.</p><a class="button" href="${issues}">Open the issue tracker <span aria-hidden="true">↗</span></a><p class="caption">Issues are public. Please leave out browsing history, session notes, email addresses and other private information.</p></div><div class="contact-choice"><h2>Send a note</h2><p>For a private question, use the project contact listed in the original Chrysalis website:</p><a class="text-link" href="mailto:elaineyouyuanche@gmail.com">elaineyouyuanche@gmail.com <span aria-hidden="true">↗</span></a><p class="caption">Opens your email application. Share only what you choose; session data is never sent automatically. No response time is promised.</p></div><h2>A useful bug report</h2><p>Tell us your extension and Chrome versions, what you expected, what happened, and the steps to reproduce it. A screenshot is optional. You do not need to share the videos you watch or your personal reflections.</p></section>` },
    '/legacy': { title: 'The original project', content: `<section class="reading"><p class="eyebrow">Where Chrysalis began</p><h1>A prototype,<br>preserved.</h1><p class="lead">Chrysalis began as an experimental social feed. Active development now focuses on the desktop YouTube extension: planning, time awareness and choices you control.</p><p>The original application’s source, assets, documentation and database migrations are preserved in the repository at tag <code>legacy-web-baseline-2026-09-07</code>. The prototype is not part of this public website.</p><p>The local baseline is already recorded. ${link(repo, 'The source repository')} will expose the named tag once it has been published.</p><h2>Existing accounts and research sessions</h2><p>The extension does not use or import old accounts, saved videos, research records or uploaded avatars. Moving to the extension does not delete that data. Service and data retirement are separate decisions.</p><p>If an old account, study or password-reset link brought you here, ${link('/contact', 'contact the project')} for help. Do not include passwords, recovery links or participant credentials in a public issue. No deletion or completed service shutdown is implied by this page.</p><a class="button" href="/">Meet the YouTube extension <span aria-hidden="true">↗</span></a></section>` },
    '/legacy-account': { title: 'Original application link', content: `<section class="reading"><p class="eyebrow">Original application</p><h1>This link belongs<br>to the prototype.</h1><p>The public website no longer runs the original sign-in, diagnostic or research interface. The YouTube extension needs no account and does not import that data.</p><p>If you need account recovery or help with an existing study session, ${link('/contact', 'contact the project privately')}. Never share a password-reset URL or participant token in a public issue.</p><p>${link('/legacy', 'Read about the preserved prototype')}</p></section>` }
  };
}
