import { chromium, expect } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
const profile = await mkdtemp(path.join(tmpdir(), 'chrysalis-experience-'));
const extensionPath = path.resolve(process.env.CHRYSALIS_EXTENSION_PATH ?? 'dist'); const checks = [], errors = [];
await mkdir('test-results', { recursive: true });
let context;
try {
 context = await chromium.launchPersistentContext(profile, { channel:'chromium', headless:true, viewport:{width:1100,height:900}, args:[`--disable-extensions-except=${extensionPath}`,`--load-extension=${extensionPath}`] });
 const worker = context.serviceWorkers()[0] ?? await context.waitForEvent('serviceworker');
 const id = new URL(worker.url()).hostname, base = `chrome-extension://${id}/`;
 context.on('page', p => p.on('pageerror', e => errors.push(e.message)));
 const popup = await context.newPage(); await popup.goto(`${base}popup.html`); await popup.setViewportSize({width:390,height:720});
 await expect(popup.locator('#intro-start')).toBeVisible(); await expect(popup.locator('#experience')).toBeHidden();
 await popup.screenshot({path:'test-results/experience-welcome.png', fullPage:true});
 await popup.locator('#intro-skip').click(); await expect(popup.locator('#intention')).toBeFocused();
 await expect(popup.locator('#time-target')).toHaveValue('15');
 const state = () => popup.evaluate(async () => (await chrome.runtime.sendMessage({channel:'chrysalis/v1',type:'GET_SNAPSHOT'})).snapshot);
 assert.equal((await state()).settings.hideHomeRecommendations, false);
 await popup.reload(); await expect(popup.locator('#introduction')).toBeHidden();
 checks.push('Introduction is short, skippable, persisted, and restores focus to the unrestricted start form.');
 const optionsPromise = context.waitForEvent('page'); await popup.locator('#viewing-preferences').click(); const options = await optionsPromise;
 await expect(options.locator('#preferences-heading')).toBeVisible();
 await options.locator('#indicator-collapsed').uncheck();
 await expect(options.locator('#default-custom')).toBeVisible(); await options.locator('#default-custom').fill('19'); await options.locator('#save-default-target').click(); await expect(options.locator('#save-status')).toHaveText('Saved on this device.'); assert.equal((await state()).settings.defaultTargetMs,19*60000); await options.locator('#default-target').selectOption('15'); await expect(options.locator('#save-status')).toHaveText('Saved on this device.');
 await options.locator('#break-preference').fill('7'); await options.locator('#save-break-preference').click(); await expect(options.locator('#save-status')).toHaveText('Saved on this device.');
 await options.locator('#checkpoints-enabled').uncheck(); await expect(options.locator('#save-status')).toHaveText('Saved on this device.');
 await popup.reload(); await expect(popup.locator('#time-target')).toHaveValue('15');
 await popup.locator('#custom-minutes').fill('23');
 await expect(popup.locator('#time-target')).toHaveValue('custom');
 await popup.locator('#intention').selectOption('custom');
 const intention = 'Exploring the connections between art and everyday life without rushing anywhere';
 await popup.locator('#custom-intention').fill(intention);
 await popup.locator('#submit-plan').click(); await expect(popup.locator('#session-phase')).toHaveText('Active');
 assert.equal((await state()).currentSession.targetMs,23*60000);
 await expect(popup.locator('#break-minutes')).toHaveValue('7');
 await expect(popup.locator('#session-intention')).toBeFocused();
 await popup.screenshot({path:'test-results/experience-session-light.png',fullPage:true});
 await popup.locator('#edit-plan').click(); await popup.locator('#cancel-edit').click(); await expect(popup.locator('#edit-plan')).toBeFocused();
 checks.push('Session preferences fill new plans and break controls; long custom intention with a time target works; edit cancellation restores focus.');
 await context.route('https://www.youtube.com/**', route => route.fulfill({contentType:'text/html',body:`<!doctype html><style>body{margin:0;font:16px sans-serif} ytd-app,ytd-watch-flexy{display:block} header{height:60px;background:#eee} #player{height:300px;background:#333;color:white} #below{max-width:800px;margin:auto} [hidden]{display:none!important}</style><ytd-app><header><input placeholder="Search"><button>Account</button></header><ytd-watch-flexy><div id="player"><video controls></video><button>Captions</button></div><div id="below"><h1>Video title</h1><p>Normal YouTube content</p></div></ytd-watch-flexy></ytd-app>`}));
 const yt = await context.newPage(); await yt.goto('https://www.youtube.com/watch?v=fixture');
 const indicator = yt.locator('#chrysalis-extension-indicator'); await expect(indicator).toBeVisible();
 await expect(indicator.locator('#intention')).toHaveText(intention);
 const ib = await indicator.boundingBox(), pb = await yt.locator('#player').boundingBox(); assert(ib.x >= 0 && ib.x + ib.width <= 1100);
 assert.equal(await indicator.locator('#time').getAttribute('aria-live'),'off');
 await indicator.getByRole('button',{name:'Collapse',exact:true}).click(); await expect(indicator.locator('#details')).toBeHidden();
 await indicator.getByRole('button',{name:'Expand',exact:true}).click(); await expect(indicator.locator('#details')).toBeVisible();
 // DOM-generated clicks must not invoke privileged session actions.
 await indicator.getByRole('button',{name:'Pause session',exact:true}).evaluate(b=>b.click()); assert.equal((await state()).currentSession.phase,'active');
 await indicator.getByRole('button',{name:'Pause session',exact:true}).click(); await expect(indicator.getByRole('button',{name:'Resume session',exact:true})).toBeFocused();
 assert.equal((await state()).currentSession.phase,'paused');
 await indicator.getByRole('button',{name:'Resume session',exact:true}).click(); await expect(indicator.getByRole('button',{name:'Pause session',exact:true})).toBeVisible();
 const editPromise = context.waitForEvent('page'); await indicator.getByRole('button',{name:'Edit plan',exact:true}).click(); const edit = await editPromise;
 await expect(edit.locator('#submit-plan')).toHaveText('Save plan'); await expect(edit.locator('#intention')).toBeFocused();
 await edit.locator('#intention').selectOption('Studying'); await edit.locator('#submit-plan').click();
 await expect(indicator.locator('#intention')).toHaveText('Studying'); await edit.close();
 await yt.screenshot({path:'test-results/experience-indicator.png',fullPage:true});
 await yt.locator('#player').evaluate(async e=> { const b=document.createElement('button'); b.id='go-full'; b.textContent='Fullscreen'; b.onclick=()=>e.requestFullscreen(); e.append(b); });
 await yt.locator('#go-full').click(); await expect.poll(()=>yt.evaluate(()=>Boolean(document.fullscreenElement))).toBe(true); await expect(indicator.locator('#restore')).toBeVisible();
 await yt.evaluate(()=>document.exitFullscreen()); await expect(indicator).toBeVisible();
 checks.push('Indicator floats within viewport bounds, shows plan/foreground time, collapses, ignores synthetic clicks, pauses/resumes/edits through real actions, and reduces to a restore tab in fullscreen.');
 await options.locator('#theme').selectOption('dark'); await expect(indicator).toHaveAttribute('data-theme','dark');
 await popup.screenshot({path:'test-results/experience-session-dark.png',fullPage:true});
 await options.emulateMedia({reducedMotion:'reduce'}); await options.setViewportSize({width:375,height:850});
 assert.equal(await options.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await options.screenshot({path:'test-results/experience-settings-narrow.png',fullPage:true});
 const tabId = await options.evaluate(async()=> (await chrome.tabs.getCurrent()).id);
 await worker.evaluate(async id=>chrome.tabs.setZoom(id,2),tabId);
 await options.screenshot({path:'test-results/experience-settings-zoom.png',fullPage:true});
 if (await options.evaluate(()=>document.documentElement.scrollWidth>innerWidth)) console.log('Zoom overflow', await options.evaluate(()=>[...document.querySelectorAll('body *')].filter(e=>e.getBoundingClientRect().right>innerWidth+1).map(e=>[e.tagName,e.id,e.getBoundingClientRect().right,innerWidth]).slice(0,20)));
 assert.equal(await options.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await worker.evaluate(async id=>chrome.tabs.setZoom(id,1),tabId);
 checks.push('Light/dark surfaces and 375px settings checked; actual Chrome tab zoom at 200% has no horizontal overflow; reduced-motion setting exercised.');
 await indicator.getByRole('button',{name:'Finish session',exact:true}).click(); await expect(popup.locator('#session-phase')).toHaveText('Finished');
 await expect(options.locator('#history-count')).toContainText('1 completed session');
 await options.locator('#clear-history').click(); await expect(options.locator('#cancel-delete')).toBeFocused();
 await options.keyboard.press('Escape'); await expect(options.locator('#clear-history')).toBeFocused();
 assert.equal((await state()).completedSessions.length,1);
 await options.locator('#clear-history').click(); await options.locator('#confirm-delete').click();
 await expect(options.locator('#history-count')).toHaveText('No completed sessions saved yet.');
 assert.equal((await state()).receipts.length,0); assert.equal((await state()).currentSession.phase,'idle');
 await popup.locator('#intention').selectOption('custom'); await popup.locator('#custom-intention').fill('Unstarted private draft');
 await options.locator('#delete-all').click(); await options.locator('#confirm-delete').click();
 await expect(options.locator('#intro-start')).toBeVisible(); await expect(options.locator('#intro-start')).toBeFocused();
 assert.equal((await state()).settings.theme,'system'); assert.equal((await state()).settings.defaultTargetMs,900000);
 assert.equal((await state()).currentSession.phase,'idle');
 await expect(popup.locator('#custom-intention')).toHaveValue('');
 checks.push('Finish saves a real summary; deletion dialog supports Escape/focus restoration; clear history and delete all remove the appropriate local data and reset defaults.');
 const saved = await state();
 await worker.evaluate(() => chrome.storage.session.set({'chrysalis.extension.v1':{schemaVersion:999}}));
 await popup.reload(); await expect(popup.locator('#intro-retry')).toBeVisible();
 assert.equal(await worker.evaluate(async()=> (await chrome.storage.session.get('chrysalis.extension.v1'))['chrysalis.extension.v1'].schemaVersion),999);
 await worker.evaluate(s=>chrome.storage.session.set({'chrysalis.extension.v1':s}),saved);
 await popup.locator('#intro-retry').click(); await expect(popup.locator('#intro-start')).toBeEnabled();
 checks.push('Delete-all clears unsaved plan fields too; invalid saved data stays untouched and first-use retry remains accessible.');
 assert.deepEqual(errors,[]);
 await writeFile('test-results/experience-report.json',JSON.stringify({browser:context.browser().version(),checks},null,2)); console.log(checks.join('\n'));
} finally {await context?.close(); await rm(profile,{recursive:true,force:true});}
