import { chromium, expect } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
const profile = await mkdtemp(path.join(tmpdir(), 'chrysalis-hardening-'));
const extension = path.resolve(process.env.CHRYSALIS_EXTENSION_PATH ?? 'dist'), checks = [];
checks.push = (...items) => { console.log(items.join('\n')); return Array.prototype.push.apply(checks, items); };
const delay = ms => new Promise(resolve => setTimeout(resolve, ms));
let context;
try {
  context = await chromium.launchPersistentContext(profile, { channel: 'chromium', headless: true, viewport: { width: 1100, height: 900 }, args: [`--disable-extensions-except=${extension}`, `--load-extension=${extension}`] });
  let worker = context.serviceWorkers()[0] ?? await context.waitForEvent('serviceworker');
  const base = `chrome-extension://${new URL(worker.url()).hostname}/`;
  let popup = await context.newPage(); await popup.goto(`${base}popup.html`); await popup.locator('#intro-skip').click();
  const state = () => popup.evaluate(async () => { const r = await chrome.runtime.sendMessage({ channel: 'chrysalis/v1', type: 'GET_SNAPSHOT' }); if (!r.ok) throw Error(r.error); return r.snapshot; });
  const options = await context.newPage(); await options.goto(`${base}options.html#viewing`);
  await options.locator('#hide-home').check(); await expect(options.locator('#save-status')).toHaveText('Saved on this device.');
  await options.evaluate(() => { location.hash = 'preferences'; });
  await options.locator('#theme').selectOption('dark'); await expect(options.locator('#save-status')).toHaveText('Saved on this device.');
  assert.equal((await state()).settings.theme, 'dark');
  checks.push('Settings save successfully after real fragment navigation to #viewing and #preferences.');
  const fixture = '<!doctype html><style>ytd-rich-item-renderer {display:block}</style><header><input aria-label="Search"></header><ytd-browse page-subtype="home"><ytd-rich-grid-renderer><div id="contents"><ytd-rich-item-renderer id="card"><div id="content"><ytd-rich-grid-media><a href="/watch?v=a">Video</a></ytd-rich-grid-media></div></ytd-rich-item-renderer></div></ytd-rich-grid-renderer></ytd-browse>';
  await context.route('https://www.youtube.com/**', r => r.fulfill({ contentType: 'text/html', body: fixture }));
  const yt = await context.newPage();
  const cdp = await context.newCDPSession(yt), worlds = new Map();
  cdp.on('Runtime.executionContextCreated', ({ context: w }) => worlds.set(w.id, w)); await cdp.send('Runtime.enable');
  await yt.goto('https://www.youtube.com/');
  await expect(yt.locator('#card')).toBeHidden();
  const world = [...worlds.values()].find(w => w.origin === base.slice(0, -1)); assert(world);
  async function isolated(expression) {
    const r = await cdp.send('Runtime.evaluate', { expression, contextId: world.id, awaitPromise: true, returnByValue: true });
    assert.equal(r.exceptionDetails, undefined, JSON.stringify(r.exceptionDetails)); return r.result.value;
  }
  await isolated('window.__chrysalisFoundation.dispose(); globalThis.observers=0; const NativeObserver=MutationObserver; globalThis.MutationObserver=class extends NativeObserver { active=false; observe(...a){if(!this.active){this.active=true;observers++}return super.observe(...a)}disconnect(){if(this.active){this.active=false;observers--}super.disconnect()} };');
  await isolated(await readFile(path.join(extension, 'content.js'), 'utf8'));
  await expect.poll(() => isolated('observers')).toBe(2);
  assert.equal(await isolated('chrome.storage.local.get().then(()=>"exposed",()=>"denied")'), 'denied');
  const forbidden = await isolated('chrome.runtime.sendMessage({channel:"chrysalis/v1",type:"GET_SNAPSHOT"})');
  assert.equal(forbidden.code, 'FORBIDDEN');
  checks.push('Actual isolated content context cannot access local storage or request private session/history snapshots.');
  const second = await context.newPage(); await second.goto('https://www.youtube.com/');
  await popup.bringToFront(); await popup.locator('#time-target').selectOption('none'); await popup.locator('#submit-plan').click();
  await yt.bringToFront(); await expect.poll(async () => (await state()).currentSession.elapsedMs, { timeout: 15000 }).toBeGreaterThanOrEqual(2000);
  await popup.evaluate(() => { window.writes = 0; window.writeDetails = []; chrome.storage.onChanged.addListener((c, area) => { if (area === 'local' && c['chrysalis.extension.v1']) { window.writes++; const s=c['chrysalis.extension.v1'].newValue; window.writeDetails.push({at:Date.now(),anchor:s.timing.anchor,signals:s.timing.signals}); } }); });
  await yt.evaluate(() => { for (let i = 0; i < 1000; i++) document.dispatchEvent(new Event('visibilitychange')); });
  await delay(6500);
  const writes = await popup.evaluate(() => window.writes);
  assert(writes >= 2 && writes <= 8, `Expected bounded two-second persistence from two content documents, got ${writes} writes: ${JSON.stringify(await popup.evaluate(() => window.writeDetails))}`);
  checks.push(`Active timing produced ${writes} snapshot writes across two YouTube documents in 6.5 seconds despite 1,000 synthetic visibility events; no render-frame writes.`);
  await options.locator('#extension-pause').click();
  await expect(popup.locator('#session-phase')).toHaveText('Paused');
  for (const p of [yt, second]) {
    await expect(p.locator('#card')).toBeVisible();
    await expect(p.locator('#chrysalis-extension-indicator, #chrysalis-viewing-style, #chrysalis-viewing-status, html[data-chrysalis-view-page]')).toHaveCount(0);
  }
  assert.equal(await isolated('observers'), 0);
  let s = await state(); const stopped = s.currentSession.elapsedMs;
  await yt.bringToFront(); await popup.evaluate(() => { window.writes = 0; }); await delay(3000);
  assert.equal((await state()).currentSession.elapsedMs, stopped); assert.equal(await popup.evaluate(() => window.writes), 0);
  await popup.reload(); await expect(popup.locator('#extension-pause')).toHaveText('Enable Chrysalis');
  await expect(popup.locator('[data-action="resume"]')).toBeDisabled();
  await popup.setViewportSize({ width: 340, height: 700 });
  await mkdir('test-results', { recursive: true }); await popup.screenshot({ path: 'test-results/hardening-paused-popup.png', fullPage: true });
  assert.equal(await popup.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await popup.locator('#extension-pause').click();
  await expect(yt.locator('#card')).toBeHidden(); await expect(second.locator('#card')).toBeHidden();
  await expect(popup.locator('#session-phase')).toHaveText('Paused');
  await expect.poll(() => isolated('observers')).toBe(2);
  checks.push('Extension-wide pause restores both tabs, removes every owned observer/style/dock, stops writes/time, persists across popup reload, and enables saved controls without resuming the session. Narrow popup has no horizontal overflow.');
  await isolated('globalThis.probes=0; const originalQuery=document.querySelector.bind(document); document.querySelector=(...a)=>{probes++;return originalQuery(...a)};');
  await yt.evaluate(() => { const fragment=document.createDocumentFragment(); for(let i=0;i<1000;i++){const e=document.createElement('span'); e.textContent='Comment'; fragment.append(e);} document.body.append(fragment); });
  await delay(800); const probes=await isolated('probes'); assert(probes < 40, `Unbounded adapter probes: ${probes}`);
  checks.push(`A batch of 1,000 unrelated inserted nodes triggered ${probes} bounded document probes, with no duplicate observers.`);
  await popup.locator('[data-action="resume"]').click(); await yt.bringToFront();
  await expect.poll(async () => (await state()).currentSession.elapsedMs, { timeout: 15000 }).toBeGreaterThan(stopped);
  const beforeGap = (await state()).currentSession.elapsedMs;
  await cdp.send('Debugger.enable'); await cdp.send('Debugger.pause'); await delay(6500);
  await cdp.send('Debugger.resume'); await cdp.send('Debugger.disable');
  s = await state();
  assert.equal(s.currentSession.phase, 'paused'); assert.equal(s.currentSession.recoveryReason, 'signal-gap');
  assert(s.currentSession.elapsedMs <= beforeGap + 1000);
  checks.push('A debugger-suspended renderer with a >5-second missing-signal gap recovers paused without crediting the gap; this is not physical OS sleep evidence.');
  await popup.locator('[data-action="finish"]').click();
  await expect(popup.locator('#session-reflection')).toBeVisible(); await popup.locator('#session-reflection [data-skip]').click();
  // Fail the real Chrome write call in this disposable worker, then recover it.
  await worker.evaluate(() => { globalThis.originalSet = chrome.storage.local.set; chrome.storage.local.set = async () => { throw Error('test storage unavailable'); }; });
  await options.locator('#theme').selectOption('light');
  await expect(options.locator('#save-status')).toContainText('could not');
  assert.equal((await state()).settings.theme, 'dark');
  await worker.evaluate(() => { chrome.storage.local.set = globalThis.originalSet; });
  await options.locator('#theme').selectOption('light'); await expect(options.locator('#save-status')).toHaveText('Saved on this device.');
  checks.push('Injected Chrome storage-write failure reports an error, preserves saved settings, and allows a successful retry without restarting the worker.');
  // Idle sessions have no foreground pulses, so this exercises the local cleanup watchdog.
  await yt.bringToFront(); await expect(yt.locator('#chrysalis-viewing-style')).toHaveCount(1);
  const manager = await context.newPage(); await manager.goto('chrome://extensions/');
  await manager.locator('extensions-toolbar').locator('#devMode').click();
  const card = manager.locator('extensions-item').filter({ hasText: 'Chrysalis' });
  const restarted = context.waitForEvent('serviceworker').catch(() => null);
  await card.locator('#dev-reload-button').click();
  await yt.bringToFront();
  await expect(yt.locator('#card')).toBeVisible({ timeout: 10000 });
  await expect(yt.locator('#chrysalis-extension-indicator, #chrysalis-viewing-style, #chrysalis-viewing-status')).toHaveCount(0);
  assert.equal(await isolated('observers'), 0);
  popup = await context.newPage(); await popup.goto(`${base}popup.html`); worker = await restarted; assert(worker, "Worker should wake when refreshed popup requests state"); s = await state(); assert.equal(s.completedSessions.length, 1); assert.equal(s.settings.hideHomeRecommendations, true);
  await yt.reload(); await expect(yt.locator('#card')).toBeHidden();
  checks.push('The real chrome://extensions Reload button invalidates the old idle content context: it removes its controls/observers within ten seconds. Settings/history survive; refreshing YouTube installs the new content script.');
  const embedded = await context.newPage(); await embedded.goto('https://www.youtube.com/embed/fixture');
  await delay(700); await expect(embedded.locator('#chrysalis-extension-indicator')).toHaveCount(0);
  checks.push('Player-only /embed documents receive no dock; controls remain accessible through the popup.');
  await manager.bringToFront();
  await expect(card).toHaveCount(1); await card.locator('#enableToggle').click();
  await yt.bringToFront(); await expect(yt.locator('#card')).toBeVisible({timeout:10000});
  await expect(yt.locator('#chrysalis-extension-indicator, #chrysalis-viewing-style, #chrysalis-viewing-status')).toHaveCount(0);
  checks.push('Disabling through the real chrome://extensions card restores the existing visible YouTube page without a refresh.');
  await writeFile('test-results/hardening-browser-report.json', JSON.stringify({ browser: context.browser().version(), checks, evidence: 'Actual unpacked extension in Chromium. Controlled YouTube-origin fixtures; storage failure injected in temporary profile; renderer suspended with CDP.' }, null, 2));
} finally { await context?.close(); await rm(profile, { recursive: true, force: true, maxRetries: 3 }); }
