import { chromium, expect } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';

const profile = await mkdtemp(path.join(tmpdir(), 'chrysalis-history-'));
const extension = path.resolve(process.env.CHRYSALIS_EXTENSION_PATH ?? 'dist'), checks = [], errors = [];
let context;
try {
  context = await chromium.launchPersistentContext(profile, { channel: 'chromium', headless: true, viewport: { width: 1100, height: 900 }, args: [`--disable-extensions-except=${extension}`, `--load-extension=${extension}`] });
  context.on('page', p => p.on('pageerror', e => errors.push(e.message)));
  const worker = context.serviceWorkers()[0] ?? await context.waitForEvent('serviceworker');
  const base = `chrome-extension://${new URL(worker.url()).hostname}/`;
  const popup = await context.newPage(); await popup.goto(`${base}popup.html`); await popup.locator('#intro-skip').click();
  const state = () => popup.evaluate(async () => { const r = await chrome.runtime.sendMessage({ channel: 'chrysalis/v1', type: 'GET_SNAPSHOT' }); if (!r.ok) throw Error(r.error); return r.snapshot; });
  const historyOpened = context.waitForEvent('page'); await popup.locator('#open-history').click(); const history = await historyOpened;
  await expect(history.locator('#history-empty')).toBeVisible(); await expect(history.locator('.history-entry')).toHaveCount(0);
  assert(history.url().endsWith('options.html#history'));
  checks.push('Real history entry point opens the local settings history section with an empty state and no sample data.');
  const intention = '<img src=x onerror="window.injected=1"> Exploring';
  await popup.bringToFront(); await popup.locator('#intention').selectOption('custom'); await popup.locator('#custom-intention').fill(intention);
  await popup.locator('#time-target').selectOption('5'); await popup.locator('#submit-plan').click();
  await expect(popup.locator('#session-phase')).toHaveText('Active');
  await context.route('https://www.youtube.com/**', r => r.fulfill({ contentType: 'text/html', body: '<!doctype html><h1>YouTube-origin history fixture</h1>' }));
  const yt = await context.newPage(); await yt.goto('https://www.youtube.com/'); await yt.bringToFront();
  await expect.poll(async () => (await state()).currentSession.elapsedMs, { timeout: 15000 }).toBeGreaterThanOrEqual(2000);
  await popup.bringToFront(); await popup.locator('#edit-plan').click(); await popup.locator('#time-target').selectOption('15'); await popup.locator('#submit-plan').click();
  await popup.locator('#break-duration').selectOption('2'); await popup.locator('[data-choice="break"]').click();
  await expect(popup.locator('#session-phase')).toHaveText('Break');
  await new Promise(resolve => setTimeout(resolve, 1200));
  await popup.locator('[data-action="end-break"]').click(); await popup.locator('[data-action="finish"]').click();
  await expect(popup.locator('#session-reflection')).toBeVisible();
  const note = '<script>window.injected=2</script> I watched what I intended.';
  await popup.locator('#session-reflection textarea').fill(note); await popup.locator('#session-reflection input[value="yes"]').check();
  await mkdir('test-results', { recursive: true });
  await popup.locator('#session-reflection').screenshot({ path: 'test-results/reflection-popup.png' });
  await popup.getByRole('button', { name: 'Save reflection', exact: true }).click();
  await expect(popup.locator('#session-reflection')).toBeHidden();
  let s = await state(); const first = s.completedSessions[0];
  assert.equal(first.reflection.answer, 'yes'); assert.equal(first.reflection.note, note);
  assert(first.history.breakMs >= 1000); assert(first.elapsedMs >= 2000);
  assert.deepEqual(first.history.targetRevisions.map(r => [r.fromMs, r.toMs]), [[300000, 900000]]);
  await expect(history.locator('.history-entry')).toHaveCount(1);
  await expect(history.locator('.history-entry h3')).toHaveText(intention);
  await expect(history.locator('.reflection-note')).toHaveText(note);
  await expect(history.locator('.target-revisions')).toContainText('5 minutes → 15 minutes');
  const values = await history.locator('.history-entry dl').evaluate(dl => Object.fromEntries([...dl.querySelectorAll('dt')].map(dt => [dt.textContent, dt.nextElementSibling.textContent])));
  const clock = ms => `${Math.floor(ms / 60000)}:${String(Math.floor(ms / 1000) % 60).padStart(2, '0')}`;
  assert.equal(values['Foreground YouTube time'], clock(first.elapsedMs)); assert.equal(values['Break time (wall-clock)'], clock(first.history.breakMs));
  assert.equal(values['Original time target'], '5 minutes'); assert.equal(values['Final time target'], '15 minutes');
  assert.equal(await history.locator('#history img, #history script').count(), 0);
  assert.equal(await history.evaluate(() => window.injected), undefined);
  assert.equal(await yt.locator('#chrysalis-extension-indicator').textContent().then(t => t.includes(note)), false);
  await mkdir('test-results', { recursive: true }); await history.locator('#history').screenshot({ path: 'test-results/history-light.png' });
  await history.locator('#theme').selectOption('dark'); await history.setViewportSize({ width: 375, height: 850 });
  await history.locator('#history').screenshot({ path: 'test-results/history-dark-narrow.png' });
  assert.equal(await history.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  checks.push('A real measured session shows stored date/intention, original/final targets, explicit revision, foreground duration, separate break duration and reflection; HTML-like text renders literally in light/dark narrow views.');
  await history.locator('.history-entry').getByRole('button', { name: 'Edit reflection' }).click();
  await history.locator('#history-reflection textarea').fill('Discard this edit');
  await history.locator('#history-reflection [data-skip]').click();
  assert.equal((await state()).completedSessions[0].reflection.note, note);
  await history.locator('.history-entry').getByRole('button', { name: 'Edit reflection' }).click();
  await history.locator('#history-reflection [data-clear]').click();
  await expect(history.locator('.saved-reflection')).toHaveText('Reflection: Not answered');
  assert.equal((await state()).completedSessions[0].reflection, null);
  checks.push('Cancel preserves an existing reflection; Clear reflection explicitly removes the answer and note without deleting the session.');
  await popup.reload(); await expect(popup.locator('#session-reflection')).toBeHidden();
  const secondPopup = await context.newPage(); await secondPopup.goto(`${base}popup.html`); await expect(secondPopup.locator('#session-reflection')).toBeHidden();
  await secondPopup.close();
  await popup.bringToFront(); await popup.locator('#time-target').selectOption('none'); await popup.locator('#submit-plan').click();
  await expect(popup.locator('#session-phase')).toHaveText('Active'); await popup.locator('[data-action="finish"]').click();
  await expect(popup.locator('#session-reflection')).toBeVisible();
  await popup.locator('#session-reflection textarea').fill('This draft is discarded by Skip'); await popup.locator('#session-reflection [data-skip]').click();
  s = await state(); const skippedId = s.completedSessions[0].id;
  assert.equal(s.completedSessions[0].reflection, null); await popup.reload(); await expect(popup.locator('#session-reflection')).toBeHidden();
  checks.push('Answered and skipped reflections do not reopen after popup reload or a second surface; Skip leaves null reflection and discards the note draft.');
  const other = await context.newPage(); await other.goto(`${base}options.html#history`);
  const skipped = other.locator(`.history-entry[data-session-id="${skippedId}"]`);
  await skipped.getByRole('button', { name: 'Add reflection' }).click();
  await other.locator('#history-reflection textarea').fill('Pending note must not recreate a deleted session');
  const staleRevision = (await state()).historyRevision;
  const row = history.locator(`.history-entry[data-session-id="${skippedId}"]`);
  await row.getByRole('button', { name: 'Delete session', exact: true }).click();
  await history.locator('#history dialog [data-cancel]').click(); await expect(row).toBeVisible(); await expect(row.getByRole('button', { name: 'Delete session', exact: true })).toBeFocused();
  await row.getByRole('button', { name: 'Delete session', exact: true }).click(); await history.locator('#history dialog [data-confirm]').click();
  await expect(other.locator('#history-reflection')).toBeHidden(); await expect(other.locator('#history-reflection textarea')).toHaveValue('');
  await expect(popup.locator('#session-phase')).toHaveText('Idle');
  const stale = await other.evaluate(async ({ id, revision }) => chrome.runtime.sendMessage({ channel: 'chrysalis/v1', type: 'HISTORY', sessionId: id, expectedRevision: revision, change: { action: 'reflect', reflection: { answer: 'no', note: 'late' } } }), { id: skippedId, revision: staleRevision });
  assert.equal(stale.ok, false); assert.equal((await state()).completedSessions.length, 1);
  checks.push('Deleting one session confirms first, updates both history views and finished popup, clears pending note fields, and rejects a stale save without recreating the record.');
  await popup.bringToFront(); await popup.locator('#submit-plan').click(); await expect(popup.locator('#session-phase')).toHaveText('Active');
  await history.locator('#clear-history').click(); await history.locator('#confirm-delete').click();
  await expect(other.locator('#history-empty')).toBeVisible(); assert.equal((await state()).currentSession.phase, 'active');
  await history.locator('#delete-all').click(); await history.locator('#confirm-delete').click();
  await expect(popup.locator('#intro-start')).toBeVisible(); s = await state();
  assert.equal(s.currentSession.phase, 'idle'); assert.equal(s.settings.theme, 'system'); assert.deepEqual(s.completedSessions, []);
  checks.push('Clear history empties all history surfaces and keeps an active session; separate reset-all clears the session and preferences as well.');
  assert.deepEqual(errors, []);
  await writeFile('test-results/history-browser-report.json', JSON.stringify({ browser: context.browser().version(), checks, note: 'Actual unpacked extension; YouTube-origin fixture supplies foreground activity. History records are generated by real session actions, not seeded sample summaries.' }, null, 2));
  console.log(checks.join('\n'));
} finally { await context?.close(); await rm(profile, { recursive: true, force: true }); }
