import { chromium, expect } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
const live = process.argv.includes('--live');
const profile = await mkdtemp(path.join(tmpdir(), 'chrysalis-integrated-'));
const ext = path.resolve(process.env.CHRYSALIS_EXTENSION_PATH ?? 'dist');
const checks = [], errors = [];
checks.push = (...items) => { console.log(items.join('\n')); return Array.prototype.push.apply(checks,items); };
let context;
await mkdir('test-results', { recursive: true });
const fixture = `<!doctype html><style>body{margin:0;font:16px system-ui}header{height:64px}ytd-app,ytd-watch-flexy{display:block}#player{height:360px;background:#24212b;color:white;width:65%}#below{margin:20px}button,input{padding:12px}#player:fullscreen{width:100%;height:100%}</style><ytd-app><header><input id="search" autofocus placeholder="Search"><button id="account">Account</button></header><ytd-watch-flexy><div id="player"><video controls></video><button id="fullscreen">Fullscreen</button></div><div id="below"><h1>YouTube watch fixture</h1><button id="next">Next video</button><button id="theater">Theater mode</button></div></ytd-watch-flexy></ytd-app><script>document.querySelector('#fullscreen').onclick=()=>document.querySelector('#player').requestFullscreen();document.querySelector('#theater').onclick=()=>{document.querySelector('#player').style.width='100%';document.querySelector('ytd-watch-flexy').setAttribute('theater','')};document.querySelector('#next').onclick=()=>{history.pushState({},'', '/watch?v=next');document.dispatchEvent(new Event('yt-navigate-finish'))};</script>`;
try {
  context = await chromium.launchPersistentContext(profile, { channel:'chromium', headless:true, viewport:{width:1280,height:900}, args:[`--disable-extensions-except=${ext}`,`--load-extension=${ext}`] });
  context.setDefaultTimeout(10000);
  context.on('page', p => p.on('pageerror', e => errors.push(e.message)));
  const worker = context.serviceWorkers()[0] ?? await context.waitForEvent('serviceworker');
  const base = `chrome-extension://${new URL(worker.url()).hostname}/`;
  if (!live) await context.route('https://www.youtube.com/**', r => r.fulfill({contentType:'text/html',body:fixture}));
  const yt = await context.newPage();
  await yt.goto(live ? 'https://www.youtube.com/watch?v=aqz-KE-bpKQ' : 'https://www.youtube.com/watch?v=fixture', {waitUntil:'domcontentloaded',timeout:45000});
  const modal = yt.locator('#chrysalis-session-dialog');
  const indicator = yt.locator('#chrysalis-extension-indicator');
  await expect(modal.locator('dialog')).toBeVisible({timeout:22000});
  await expect(modal).toHaveCount(1);
  await expect(modal.locator('#duration')).toBeFocused();
  const box = await modal.locator('dialog').boundingBox();
  assert(Math.abs(box.x + box.width / 2 - 640) < 3);
  assert(Math.abs(box.y + box.height / 2 - 450) < 3);
  await yt.screenshot({path:`test-results/integrated-${live?'live':'fixture'}-intro.png`});
  await modal.locator('#close').focus(); await yt.keyboard.press('Shift+Tab');
  await expect(modal.locator('[type="submit"]')).toBeFocused();
  await yt.keyboard.press('Escape'); await expect(modal).toHaveCount(0);
  if (!live) { await expect(yt.locator('#search')).toBeFocused(); await yt.locator('#search').fill('Ordinary YouTube interaction'); }
  await yt.reload({waitUntil:'domcontentloaded'}); await expect(indicator).toBeVisible();
  await yt.waitForTimeout(1500); await expect(modal).toHaveCount(0);
  checks.push('First visit opens one centered introduction; native focus containment, Escape, restored interaction and refresh suppression verified.');
  // Advance only the visit metadata, not timing, to represent a later visit.
  await worker.evaluate(async()=>{const key='chrysalis.visit',v=(await chrome.storage.session.get(key))[key];v.lastSeen=Date.now()-1800001;await chrome.storage.session.set({[key]:v});});
  const popup = await context.newPage(); await popup.goto(`${base}popup.html`);
  const state = () => popup.evaluate(async()=>(await chrome.runtime.sendMessage({channel:'chrysalis/v1',type:'GET_SNAPSHOT'})).snapshot);
  await yt.bringToFront();
  await expect(modal.locator('dialog')).toBeVisible({timeout:22000});
  await modal.locator('#start-form').evaluate(form=>form.requestSubmit());
  assert.equal((await state()).currentSession.phase,'idle','scripted submit must not start a session');
  await modal.locator('#duration').selectOption('custom'); await modal.locator('#minutes').fill('2');
  await modal.locator('#intention').fill('Learn one useful thing');
  await modal.getByRole('button',{name:'Start session',exact:true}).click();
  await expect(modal).toHaveCount(0);
  await expect(indicator.locator('#compact')).toContainText('left');
  await expect(indicator.locator('#details')).toBeHidden();
  await expect(popup.locator('#session-phase')).toHaveText('Active');
  await expect(popup.locator('#experience')).toBeVisible();
  await indicator.locator('#collapse').click(); await expect(indicator.locator('#intention')).toHaveText('Learn one useful thing');
  await expect(indicator.locator('#viewing-state')).toContainText('Shorts entries visible');
  await indicator.locator('#collapse').click();
  await yt.screenshot({path:`test-results/integrated-${live?'live':'fixture'}-timer.png`});
  const id = (await state()).currentSession.id;
  if (!live) { await yt.locator('#next').click(); await expect(yt).toHaveURL(/v=next/); }
  await yt.reload({waitUntil:'domcontentloaded'}); await expect(indicator).toHaveCount(1); await expect(modal).toHaveCount(0);
  assert.equal((await state()).currentSession.id,id);
  const second = await context.newPage(); await second.goto('https://www.youtube.com/', {waitUntil:'domcontentloaded',timeout:45000});
  await expect(second.locator('#chrysalis-extension-indicator')).toHaveCount(1);
  await expect(second.locator('#chrysalis-session-dialog')).toHaveCount(0);
  await yt.bringToFront();
  const before = (await state()).currentSession.elapsedMs, start = Date.now();
  await yt.waitForTimeout(4200); await second.bringToFront(); await second.waitForTimeout(4200);
  const after = (await state()).currentSession.elapsedMs;
  assert(after > before); assert(after - before <= Date.now() - start + 1000);
  await popup.bringToFront(); await popup.waitForTimeout(500); const away = (await state()).currentSession.elapsedMs;
  await popup.waitForTimeout(3000); assert.equal((await state()).currentSession.elapsedMs,away);
  await second.close(); await yt.bringToFront();
  await indicator.locator('#dismiss').click(); await expect(indicator.locator('#panel')).toBeHidden();
  const hiddenTime = (await state()).currentSession.elapsedMs;
  await yt.waitForTimeout(4200); assert((await state()).currentSession.elapsedMs > hiddenTime);
  await indicator.locator('#restore').click(); await expect(indicator.locator('#panel')).toBeVisible();
  await indicator.locator('[data-action="pause"]').click();
  await expect(indicator.locator('#phase')).toHaveText('Paused by you');
  const paused = (await state()).currentSession.elapsedMs;
  await yt.waitForTimeout(2200); assert.equal((await state()).currentSession.elapsedMs,paused);
  await indicator.locator('[data-action="resume"]').click(); await expect(popup.locator('#session-phase')).toHaveText('Active');
  checks.push('Page start and popup agree; SPA/refresh retain ID; multiple tabs do not double-count; time away/manual pause excluded; hidden timer keeps counting and restores.');
  const options = await context.newPage(); await options.goto(`${base}options.html`);
  await options.locator('#theme').selectOption('dark'); await options.locator('#auto-session-intro').uncheck();
  await yt.bringToFront(); await expect(indicator).toHaveAttribute('data-theme','dark');
  await yt.emulateMedia({reducedMotion:'reduce'}); await yt.setViewportSize({width:375,height:700});
  await expect(indicator.locator('#restore')).toBeVisible();
  await indicator.locator('#restore').click(); await indicator.locator('#collapse').click();
  let panel = await indicator.locator('#panel').boundingBox(); assert(panel.x >= 0 && panel.x + panel.width <= 375 && panel.y+panel.height<=700);
  await yt.screenshot({path:`test-results/integrated-${live?'live':'fixture'}-narrow-dark.png`});
  await indicator.locator('#dismiss').click(); await yt.setViewportSize({width:1280,height:900}); await indicator.locator('#restore').click();
  if (!live) {
    await yt.locator('#theater').click(); await expect(indicator).toHaveCount(1);
    await yt.locator('#fullscreen').click();
    await expect.poll(()=>yt.evaluate(()=>Boolean(document.fullscreenElement))).toBe(true);
    await expect(indicator.locator('#restore')).toBeVisible();
    await indicator.locator('#restore').click(); await expect(indicator.locator('[data-action="pause"]')).toBeVisible();
    await yt.evaluate(()=>document.exitFullscreen());
    const tabId=await worker.evaluate(async()=> (await chrome.tabs.query({active:true,lastFocusedWindow:true}))[0].id);
    await worker.evaluate(id=>chrome.tabs.setZoom(id,2),tabId);
    await expect(indicator.locator('#restore')).toBeVisible(); await indicator.locator('#restore').click();
    panel=await indicator.locator('#panel').boundingBox(); const width=await yt.evaluate(()=>innerWidth); assert(panel.x>=0&&panel.x+panel.width<=width);
    await worker.evaluate(id=>chrome.tabs.setZoom(id,1),tabId);
  }
  checks.push(`Dark mode, reduced motion and 375px widget bounds checked${live?'':'; fixture theater, fullscreen restore and real 200% Chrome zoom checked'}.`);
  // Seed near the target; real observations perform the crossing.
  await worker.evaluate(async()=>{const k='chrysalis.extension.v1',s=(await chrome.storage.session.get(k))[k];s.currentSession.elapsedMs=119000;s.timing.anchor=null;s.sequence++;await chrome.storage.session.set({[k]:s});});
  await yt.bringToFront(); await expect(modal.locator('dialog')).toBeVisible({timeout:20000});
  await expect(modal.locator('#dialog-title')).toHaveText('A moment to choose.');
  await modal.locator('#additional-duration').selectOption('5');
  await modal.locator('[data-choice="extend"]').click(); await expect(modal).toHaveCount(0);
  assert((await state()).currentSession.targetMs>=419000);
  await worker.evaluate(async()=>{const k='chrysalis.extension.v1',s=(await chrome.storage.session.get(k))[k];s.currentSession.elapsedMs=s.currentSession.targetMs-1000;s.timing.anchor=null;s.sequence++;await chrome.storage.session.set({[k]:s});});
  await expect(modal.locator('dialog')).toBeVisible({timeout:20000});
  await modal.locator('[data-choice="break"]').click(); await expect(popup.locator('#session-phase')).toHaveText('Break');
  if (await indicator.locator('#restore').isVisible()) await indicator.locator('#restore').click();
  if (await indicator.locator('#details').isHidden()) await indicator.locator('#collapse').click();
  await indicator.locator('[data-action="end-break"]').click(); await expect(popup.locator('#session-phase')).toHaveText('Paused');
  await indicator.locator('[data-action="resume"]').click();
  await indicator.locator('[data-action="finish"]').click(); await expect(popup.locator('#session-phase')).toHaveText('Finished');
  await yt.reload({waitUntil:'domcontentloaded'}); await yt.waitForTimeout(1000); await expect(modal).toHaveCount(0);
  checks.push('Real pulses trigger centered check-ins; deliberate extension rearms; break ends paused; resume and finish sync to popup; disabled auto-intro stays off.');
  console.log('Verifying optional intention and introduction dismissal');
  await options.locator('#auto-session-intro').check();
  const laterVisit = async () => {
    await popup.bringToFront();
    await worker.evaluate(async()=>{const key='chrysalis.visit',v=(await chrome.storage.session.get(key))[key];v.lastSeen=Date.now()-1800001;await chrome.storage.session.set({[key]:v});});
    await yt.bringToFront();
    await expect(modal.locator('dialog')).toBeVisible({timeout:22000});
  };
  await laterVisit(); await modal.locator('#close').click();
  await expect(modal).toHaveCount(0); assert.equal((await state()).currentSession.phase,'finished');
  await laterVisit(); await modal.locator('#duration').selectOption('custom'); await modal.locator('#minutes').fill('1');
  await modal.locator('#intention').focus(); await yt.keyboard.press('Enter');
  await expect(modal).toHaveCount(0); assert.equal((await state()).currentSession.intention,'Your session');
  await worker.evaluate(async()=>{const k='chrysalis.extension.v1',s=(await chrome.storage.session.get(k))[k];s.currentSession.elapsedMs=59000;s.timing.anchor=null;s.sequence++;await chrome.storage.session.set({[k]:s});});
  await expect(modal.locator('dialog')).toBeVisible({timeout:20000}); await modal.locator('#finish').click();
  await expect(popup.locator('#session-phase')).toHaveText('Finished');
  checks.push('Dismissing the introduction creates no session; optional empty intention and Enter submission work; scripted submit is ignored; centered Finish saves the session.');
  if(!live)assert.deepEqual(errors,[]);
  await writeFile(`test-results/integrated-${live?'live':'fixture'}-report.json`,JSON.stringify({browser:context.browser().version(),kind:live?'Live signed-out YouTube':'Unpacked extension on controlled YouTube fixtures',checks,errors,limitations:['No physical screen reader or native toolbar-popup usability test.',...(live?['Live fullscreen and theater controls not exercised in this run.']:[])]},null,2));
  console.log('Integrated browser checks passed.');
} finally { await context?.close(); await rm(profile,{recursive:true,force:true}); }
