// Capture the actual action popup target, which Playwright does not expose as a Page.
import {chromium,expect} from '@playwright/test';
import {mkdtemp,rm,writeFile,mkdir} from 'node:fs/promises';import {tmpdir} from 'node:os';import path from 'node:path';
const out=path.resolve(process.env.CHRYSALIS_USABILITY_OUTPUT ?? '../screenshots/chrysalis-usability');await mkdir(out,{recursive:true});const profile=await mkdtemp(path.join(tmpdir(),'chrysalis-native-'));let context;const checks=[];
try {
 const ext=path.resolve(process.env.CHRYSALIS_EXTENSION_PATH??'dist');context=await chromium.launchPersistentContext(profile,{channel:'chromium',headless:true,args:[`--disable-extensions-except=${ext}`,`--load-extension=${ext}`]});const worker=context.serviceWorkers()[0]??await context.waitForEvent('serviceworker');
 const anchor=await context.newPage();await anchor.goto('about:blank');const cdp=await context.newCDPSession(anchor);
 let sequence=0;const pending=new Map();
 cdp.on('Target.receivedMessageFromTarget',({message})=>{const m=JSON.parse(message),p=pending.get(m.id);if(p){pending.delete(m.id);m.error?p.reject(new Error(JSON.stringify(m.error))):p.resolve(m.result);}});
 async function attach(){await worker.evaluate(()=>chrome.action.openPopup());let target;await expect.poll(async()=>{target=(await cdp.send('Target.getTargets')).targetInfos.find(t=>t.url.endsWith('/popup.html'));return !!target;}).toBe(true);const {sessionId}=await cdp.send('Target.attachToTarget',{targetId:target.targetId,flatten:false});return {target,send(method,params={}){const id=++sequence;return new Promise((resolve,reject)=>{const timeout=setTimeout(()=>{pending.delete(id);reject(new Error(`Native CDP timeout: ${method}`));},10000);pending.set(id,{resolve:r=>{clearTimeout(timeout);resolve(r);},reject:e=>{clearTimeout(timeout);reject(e);}});void cdp.send('Target.sendMessageToTarget',{sessionId,message:JSON.stringify({id,method,params})}).catch(reject);});}};}
 let popup=await attach();const evaluate=async expression=>(await popup.send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true})).result.value;
 async function capture(name){const {data}=await popup.send('Page.captureScreenshot',{format:'png'});await writeFile(`${out}/after-native-${name}.png`,Buffer.from(data,'base64'));}
 async function click(selector){const point=await evaluate(`(()=>{const e=document.querySelector(${JSON.stringify(selector)});e.scrollIntoView({block:'center'});const r=e.getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2};})()`);await popup.send('Input.dispatchMouseEvent',{type:'mousePressed',button:'left',clickCount:1,...point});await popup.send('Input.dispatchMouseEvent',{type:'mouseReleased',button:'left',clickCount:1,...point});}
 await expect.poll(()=>evaluate('!!document.querySelector("#intro-skip")')).toBe(true);await expect.poll(()=>evaluate('innerWidth')).toBe(390);await capture('welcome');checks.push({targetType:popup.target.type,dimensions:await evaluate('({width:innerWidth,height:innerHeight})')});
 await click('#intro-skip');await expect.poll(()=>evaluate('document.querySelector("#introduction").hidden')).toBe(true);await evaluate('scrollTo(0,0)');await capture('setup');
 await click('#submit-plan');await expect.poll(()=>evaluate('document.querySelector("#session-phase").textContent')).toBe('Active');await capture('active');await click('[data-action="pause"]');await expect.poll(()=>evaluate('document.querySelector("#session-phase").textContent')).toBe('Paused');
 await cdp.send('Target.closeTarget',{targetId:popup.target.targetId});popup=await attach();await expect.poll(()=>evaluate('document.querySelector("#session-phase")?.textContent')).toBe('Paused');checks.push('Actual API-opened action popup: skip, start, pause, close and persisted reopen. Trusted CDP mouse input; no ordinary popup.html tab substitution. Physical toolbar positioning remains manual.');
 await writeFile(`${out}/after-native-report.json`,JSON.stringify({browser:context.browser().version(),checks},null,2));console.log(checks);
}finally{await context?.close();await rm(profile,{recursive:true,force:true});}
