import {chromium,expect} from '@playwright/test';import assert from 'node:assert/strict';import {mkdtemp,mkdir,rm,writeFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import path from 'node:path';
const out=path.resolve('test-results/usability');await mkdir(out,{recursive:true});const profile=await mkdtemp(path.join(tmpdir(),'chrysalis-review-live-'));let context;const results=[];
try {
 const ext=path.resolve(process.env.CHRYSALIS_EXTENSION_PATH??'dist');context=await chromium.launchPersistentContext(profile,{channel:'chromium',headless:true,viewport:{width:1440,height:1000},colorScheme:'light',args:[`--disable-extensions-except=${ext}`,`--load-extension=${ext}`]});const worker=context.serviceWorkers()[0]??await context.waitForEvent('serviceworker');const base=`chrome-extension://${new URL(worker.url()).hostname}/`;
 const popup=await context.newPage();await popup.goto(`${base}popup.html`);await popup.locator('#intro-skip').click();await popup.locator('#time-target').selectOption('custom');await popup.locator('#custom-minutes').fill('1');await popup.locator('#submit-plan').click();
 const settings=await context.newPage();await settings.goto(`${base}options.html`);
 const page=await context.newPage();await page.goto('https://www.youtube.com/watch?v=aqz-KE-bpKQ',{waitUntil:'domcontentloaded',timeout:45000});const indicator=page.locator('#chrysalis-extension-indicator'),player=page.locator('#movie_player');await expect(indicator).toBeVisible({timeout:25000});
 const shot=async name=>page.screenshot({path:`${out}/after-live-${name}.png`});
 const step=async(name,run)=>{console.log('Checking:',name);try{await run();results.push({name,status:'Pass'});}catch(e){results.push({name,status:String(e).includes('BASELINE_UNAVAILABLE')?'Blocked':'Fail',detail:String(e).slice(0,650)});}};
 const shortHref=await page.locator('a[href^="/shorts/"]').first().getAttribute('href').catch(()=>null);
 await step('Standard player / indicator geometry',async()=>{const p=await player.boundingBox(),i=await indicator.boundingBox();assert(i.y>=p.y+p.height-1);await shot('standard');});
 await step('Theater mode and in-flow indicator',async()=>{await player.hover();await player.locator('.ytp-size-button').click({timeout:5000});await expect(page.locator('ytd-watch-flexy')).toHaveAttribute('theater','');const p=await player.boundingBox(),i=await indicator.boundingBox();assert(i.y>=p.y+p.height-1);await shot('theater');});
 await step('Live fullscreen hides dock and preserves fullscreen',async()=>{await player.hover();await player.locator('.ytp-fullscreen-button').click();await expect.poll(()=>page.evaluate(()=>!!document.fullscreenElement)).toBe(true);await expect(indicator).toBeHidden();await shot('fullscreen');await player.hover();await player.locator('.ytp-fullscreen-button').click();await expect.poll(()=>page.evaluate(()=>!!document.fullscreenElement)).toBe(false);await expect(indicator).toBeVisible();});
 if(await page.evaluate(()=>!!document.fullscreenElement))await page.evaluate(()=>document.exitFullscreen());
 await step('Device-dark extension on independently light YouTube',async()=>{await page.emulateMedia({colorScheme:'dark'});await expect(indicator).toHaveAttribute('data-theme','system');assert.equal(await indicator.locator('.panel').evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(34, 28, 48)');await indicator.scrollIntoViewIfNeeded();await shot('theme-mismatch');results.push({name:'Observed host appearance',status:'Pass',detail:await page.evaluate(()=>({youtubeDark:document.documentElement.hasAttribute('dark'),deviceDark:matchMedia('(prefers-color-scheme:dark)').matches}))});});
 await step('Explicit light appearance / narrow window / 200% zoom',async()=>{await settings.locator('#theme').selectOption('light');await expect(indicator).toHaveAttribute('data-theme','light');await page.setViewportSize({width:768,height:900});const tab=await worker.evaluate(async()=> (await chrome.tabs.query({active:true,lastFocusedWindow:true}))[0].id);await worker.evaluate(id=>chrome.tabs.setZoom(id,2),tab);await indicator.scrollIntoViewIfNeeded();const bounds=await indicator.locator('.panel').boundingBox();assert(bounds.x>=0 && bounds.x+bounds.width<=await page.evaluate(()=>innerWidth));await shot('narrow-zoom');await worker.evaluate(id=>chrome.tabs.setZoom(id,1),tab);await page.setViewportSize({width:1440,height:1000});});
 await page.bringToFront();
 if(!process.argv.includes('--layout-only')) {
 await step('Real one-minute target, collapsed checkpoint and target-preserving dismissal',async()=>{await indicator.locator('#collapse').click();await expect.poll(()=>indicator.locator('#phase').textContent(),{timeout:90000}).toContain('Time target reached');await expect(indicator.locator('#details')).toBeHidden();await indicator.scrollIntoViewIfNeeded();await shot('collapsed-checkpoint');await indicator.locator('#collapse').click();await expect(indicator.locator('#checkpoint-controls')).toBeVisible();await indicator.locator('[data-choice="dismiss-checkpoint"]').click();await expect(indicator.locator('#phase')).toHaveText('Session active');});
 await step('Live break countdown, early ending and video stays playing',async()=>{await page.locator('#movie_player').hover();const media=player.locator('video').first();if(await media.evaluate(v=>v.paused))await player.locator('.ytp-play-button').click();const start=await media.evaluate(v=>v.currentTime);try{await expect.poll(()=>media.evaluate(v=>v.currentTime),{timeout:10000}).toBeGreaterThan(start+.2);}catch{throw new Error('BASELINE_UNAVAILABLE '+JSON.stringify(await media.evaluate(v=>({paused:v.paused,readyState:v.readyState,networkState:v.networkState,error:v.error?.code}))));}await indicator.locator('[data-choice="break"]').click();await expect(indicator.locator('#break-countdown')).toBeVisible();await indicator.locator('#collapse').click();const old=await indicator.locator('#compact').textContent();await expect.poll(()=>indicator.locator('#compact').textContent()).not.toBe(old);await shot('collapsed-break');results.push({name:'Break playback diagnostic',status:'Pass',detail:await media.evaluate(v=>({paused:v.paused,readyState:v.readyState,time:v.currentTime}))});assert.equal(await media.evaluate(v=>v.paused),false);await indicator.locator('#collapse').click();await indicator.locator('[data-action="end-break"]').click();await expect(indicator.locator('#phase')).toHaveText('Session paused');});
 }
 const mini=player.locator('.ytp-miniplayer-button');if(await mini.isVisible())await step('Live miniplayer preserves platform controls',async()=>{await mini.click();await expect(page.locator('ytd-miniplayer')).toBeVisible();await shot('miniplayer');});else results.push({name:'Live miniplayer',status:'Not tested',detail:'YouTube did not expose a visible miniplayer button on this video.'});
 results.push({name:'Actual rendered captions / ads / playlist queue / live chat',status:'Not tested',detail:'No usable caption track, active ad, playlist queue or chat supplied in this observed video; node-preservation fixtures are separate evidence.'});
 if(shortHref)await step('Direct Shorts URL remains available',async()=>{await settings.locator('#hide-shorts').check();await page.goto(`https://www.youtube.com${shortHref}`,{waitUntil:'domcontentloaded',timeout:45000});await expect(page.locator('ytd-shorts')).toBeVisible({timeout:20000});await shot('shorts');assert.equal(await page.locator('#chrysalis-extension-indicator').count(),0);});else results.push({name:'Direct Shorts URL',status:'Not tested',detail:'No live Shorts link supplied.'});
 await step('Live refresh and back/forward avoid duplicate mounts',async()=>{await page.goBack({waitUntil:'domcontentloaded'});await page.reload({waitUntil:'domcontentloaded'});await expect(indicator).toHaveCount(1,{timeout:25000});await page.goForward({waitUntil:'domcontentloaded'});assert((await indicator.count())<=1);});
 await writeFile(`${out}/${process.argv.includes('--layout-only')?'after-live-layout-report':'after-live-modes-report'}.json`,JSON.stringify({browser:context.browser().version(),category:'Live signed-out YouTube with real unpacked extension; no mocked responses or seeded timing',results},null,2));console.log(JSON.stringify(results,null,2));process.exitCode=results.some(r=>r.status==='Fail')?1:0;
}finally{await context?.close();await rm(profile,{recursive:true,force:true});}
